Repository artursanntos/vfoods, pull requests merged in 2023-10, with the labels that each got.

#21 Dev/general UI fixes
  src/contexts/IndicatorContext.tsx
  src/contexts/VfoodsContext.tsx
  src/index.css
  src/pages/Home.tsx
  src/pages/Indicators.tsx
  src/pages/NewIndicator.tsx
  src/pages/Profile.tsx
  src/pages/Ranking.tsx
Labels: bug

#26 Botões: Criar Indicador + Criar Colab.
  src/assets/personWhite.png
  src/componets/Atomos/ButtonAddColab.tsx
  src/componets/Atomos/ButtonAddInd.tsx
  src/pages/Home.tsx
Labels: hacktoberfest-accepted

#25 Dev/perfil colaborador
  package-lock.json
  package.json
  src/assets/mail.svg
  src/assets/phone.svg
  src/assets/star.svg
  src/componets/Collaborator/CollaboratorCard.tsx
  src/componets/Collaborator/IndicatorCardInfo.tsx
  src/componets/Collaborator/IndicatorItem.tsx
  src/componets/Collaborator/IndicatorsList.tsx
  src/componets/Header/Header.tsx
  src/componets/Header/SearchBar.tsx
  src/componets/Indicator/ColaboradoresPage.tsx
  src/componets/SideBar/SideBar.tsx
  src/contexts/VfoodsContext.tsx
  src/pages/Collaborator.tsx
  src/pages/Home.tsx
  src/types.tsx
Labels: enhancement, hacktoberfest-accepted

#22 (feat): Tela de colaboradores ranqueada
  src/App.tsx
  src/assets/starGray.svg
  src/componets/SideBar/SideBar.tsx
  src/pages/Collaborators.tsx
  src/pages/Ranking.tsx
Labels: enhancement, hacktoberfest-accepted

#27 feature: adição de toaster nos avisos, finalização do new_collaborator, e boa evolção na edição de indicador.
  package-lock.json
  package.json
  src/componets/IndicadorCardGraph.tsx
  src/componets/Indicator/ColaboradoresPage.tsx
  src/componets/Indicator/DadosPage.tsx
  src/componets/Indicator/IndicatorModal.tsx
  src/componets/SideBar/SideBar.tsx
  src/contexts/IndicatorContext.tsx
  src/contexts/VfoodsContext.tsx
  src/pages/Indicators.tsx
  src/pages/NewCollaborator.tsx
Labels: enhancement, hacktoberfest-accepted

#28 (feat): Search Bar funcional
  src/componets/Header/SearchBar.tsx
  src/pages/Collaborators.tsx
Labels: enhancement, hacktoberfest-accepted

#29 Tela base de Profile + Correção de botões do profile
  src/assets/mailGest.png
  src/componets/Atomos/ButtonAddColab.tsx
  src/componets/Atomos/ButtonAddInd.tsx
  src/componets/Gestor/GestorCard.tsx
  src/pages/Home.tsx
  src/pages/Profile.tsx
Labels: hacktoberfest-accepted

#32 fix: erro de escrita no indicator context
  src/contexts/IndicatorContext.tsx
Labels: hacktoberfest-accepted

#35 Bug fixes
  package-lock.json
  src/componets/IndicadorCardGraph.tsx
  src/componets/Indicator/ColaboradoresPage.tsx
  src/componets/Indicator/EditIndicator.tsx
  src/contexts/VfoodsContext.tsx
  src/main.tsx
  src/pages/Home.tsx
  src/pages/NewCollaborator.tsx
  src/types.tsx
Labels: bug, hacktoberfest-accepted

#36 (fix): Arrumei string de acordo com o mês
  src/pages/Collaborators.tsx
Labels: bug, enhancement, hacktoberfest-accepted

#37 (fix): Arrumar bugs da Search Bar
  src/componets/Header/SearchBar.tsx
Labels: enhancement, hacktoberfest-accepted

#31 Dev/perfil colaborador
  src/componets/CollabCardGraph.tsx
  src/componets/Collaborator/CollaboratorCard.tsx
  src/componets/Collaborator/IndicatorsList.tsx
  src/componets/SideBar/SideBar.tsx
  src/pages/Collaborator.tsx
Labels: hacktoberfest-accepted

#38 fix: fotinhas agora são sempre redondas no perfil do collab
  src/componets/Collaborator/CollaboratorCard.tsx
Labels: hacktoberfest-accepted

#39 Estruturação do README
  README.md
Labels: documentation, hacktoberfest-accepted

#41 feat: grafico de indicadores funcional e integrado
  src/componets/CollabCardGraph.tsx
  src/componets/CollabLineGraph.tsx
  src/componets/Collaborator/IndicatorsList.tsx
  src/componets/LineGraph.tsx
  src/contexts/ColaboratorContext.tsx
  src/pages/Collaborator.tsx
Labels: enhancement

#42 (fix): Movi o botão pra cima
  src/pages/Collaborators.tsx
Labels: enhancement, hacktoberfest-accepted

#44 fix: atualizada requisicao grafico colaborador
  src/componets/CollabCardGraph.tsx
  src/componets/CollabLineGraph.tsx
Labels: bug

#45 Editando indicador
  src/componets/IndicadorCardGraph.tsx
  src/componets/Indicator/ColaboradoresPage.tsx
  src/componets/Indicator/DadosPage.tsx
  src/componets/Indicator/EditIndicator.tsx
  src/componets/Indicator/IndicatorModal.tsx
  src/componets/Indicator/MetasPage.tsx
  src/contexts/IndicatorContext.tsx
  src/pages/Indicators.tsx
  src/pages/NewIndicator.tsx
Labels: enhancement, hacktoberfest-accepted

#47 Dev/homepage
  index.html
  public/logo.svg
  src/componets/HomePageGraph.tsx
  src/componets/HomePageLineGraph.tsx
  src/componets/Homepage/CollabTable.tsx
Labels: enhancement

#48 Melhorada aparência da Search Bar
  src/componets/Header/SearchBar.tsx
  src/componets/Header/assets/IconSearch.png
Labels: enhancement

#49 Finalizações no perfil do gestor
  src/componets/Atomos/ButtonAddInd.tsx
  src/componets/Gestor/CardPizza.tsx
  src/componets/Gestor/GestorCard.tsx
  src/componets/Gestor/GestorGraphPizza.tsx
  src/componets/Gestor/InfoCard.tsx
  src/pages/Profile.tsx
Labels: enhancement, hacktoberfest-accepted

#54 Pagina indicador
  src/componets/Indicator/DadosPage.tsx
  src/pages/IndicatorPage.tsx
Labels: bug, hacktoberfest-accepted

#59 fixes: limpeza do código
  src/componets/Atomos/Textbox.tsx
  src/componets/CardGraphIndicator.tsx
  src/componets/Header/SearchBar.tsx
  src/componets/Homepage/CollabTable.tsx
  src/componets/Indicator/IndicadorCardGraph.tsx
  src/componets/Indicator/IndicadorPageCardGraph.tsx
  src/contexts/ColaboratorContext.tsx
  src/pages/IndicatorPage.tsx
  src/pages/NewCollaborator.tsx
Labels: documentation, hacktoberfest-accepted

#60 tabela dos colaboradores da página do indicador
  src/componets/Indicator/CollaboratorsTable.tsx
  src/pages/IndicatorPage.tsx
Labels: enhancement, hacktoberfest-accepted

#65 feature: mudança de nome entre criado e editado
  src/componets/Indicator/IndicatorModal.tsx
  src/pages/NewIndicator.tsx
Labels: enhancement, hacktoberfest-accepted
